name: qr_generator_and_scanner
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Scanner QR Code dengan kamera
  mobile_scanner: ^7.1.4

  # Permission handler untuk akses kamera & storage
  permission_handler: ^12.0.1

  # Generator QR Code
  pretty_qr_code: ^3.5.0

  # Screenshot widget
  screenshot: ^3.0.0

  # Share ke aplikasi lain
  share_plus: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # UI Testing preview
  device_preview: ^1.3.1

flutter:
  uses-material-design: true

  # Konfigurasi Assets
  assets:
    - assets/images/

  # Konfigurasi Font Kustom
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700